### ISSUE TITLE
Incorrect Animation

### ISSUE THREAD

**Issue by Shvier** [andrespch/CubicCollectionViewController#1]
Hi~
I'd like to do a same app as yours recently.
I tried my own way(use scrollView) but its performance is not satisfied.
Then I use your project.But the animation seems like dislocation and the Example is empty.
Sincerely wait for your reply.

**Comment by Shvier** [comment]
Oh, I found that bug because of the collectionViewCell reuse pool.
Just reset the transform or frame of the reuse cell, then it works perfectly.

**Comment by andrespch** [comment]
sorry for the super long response @Shvier  if it helps I also uploaded a Layout subclass that achieves the same.
